"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
from pathlib import Path

from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure--cebrcum099t+(=)o=id)q+!d6w+*f+bq*v&8a-q6l$x1o6&ri',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

_ON_RENDER = os.getenv("RENDER", "").lower() in ("1", "true", "yes")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'axes',
    'django_celery_beat',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'tracker',
]

_MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if os.getenv("USE_WHITENOISE", "").lower() in ("1", "true", "yes") or _ON_RENDER:
    _MIDDLEWARE.append("whitenoise.middleware.WhiteNoiseMiddleware")
_MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-axes: must come AFTER AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    'tracker.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE = _MIDDLEWARE

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'commission_decision'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': int(os.getenv('CONN_MAX_AGE', '300')),
        'OPTIONS': {
            'connect_timeout': int(os.getenv('POSTGRES_CONNECT_TIMEOUT', '10')),
        },
    }
}

if os.getenv('USE_SQLITE', '').lower() in ('1', 'true', 'yes'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Render.com / Heroku-style DATABASE_URL (takes precedence over POSTGRES_*)
_database_url = os.getenv("DATABASE_URL", "").strip()
if _database_url:
    import dj_database_url

    DATABASES["default"] = dj_database_url.config(
        default=_database_url,
        conn_max_age=int(os.getenv("CONN_MAX_AGE", "600")),
        conn_health_checks=True,
        ssl_require=_database_url.startswith("postgres") and "sslmode=disable" not in _database_url,
    )

# Optional single REDIS_URL for managed Redis (Render Key Value)
_redis_url = os.getenv("REDIS_URL", "").strip()
if _redis_url and not os.getenv("CELERY_BROKER_URL"):
    os.environ["CELERY_BROKER_URL"] = _redis_url
    os.environ["CELERY_RESULT_BACKEND"] = os.getenv("CELERY_RESULT_BACKEND", _redis_url)

_BEHIND_PROXY = _ON_RENDER or os.getenv("DJANGO_BEHIND_PROXY", "").lower() in ("1", "true", "yes")
if _BEHIND_PROXY:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    if not DEBUG:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Efate'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Leading slash for same-origin Docker/nginx; full API URL on Render (SPA on another host).
MEDIA_ROOT = os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media"))
_cdp_public = os.getenv("CDP_BASE_URL", "").strip().rstrip("/")
if _cdp_public and not DEBUG:
    MEDIA_URL = f"{_cdp_public}/media/"
else:
    MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'tracker.auth.APIKeyAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '300/min',
        'user': '600/min',
        'otp_request':     '5/min',
        'otp_verify':      '10/min',
        'password_reset':  '5/min',
        'password_change': '10/min',
        'submission_create': '10/hour',
        'feedback_create':   '5/hour',
        'staff_chat':        '60/hour',
        'session_pin_verify': '5/min',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'SCDMS API',
    'DESCRIPTION': 'Submission & Commission Decision Management System — REST API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

from datetime import timedelta

SIMPLE_JWT = {
    # Reduced from 120 min → 30 min for NCSS 2030 session security
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '30'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    # Rotate refresh tokens and blacklist old ones on each use
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

# ── django-axes: Account lockout (NCSS 2030 — Brute-force protection) ─────────
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(hours=int(os.getenv('AXES_COOLOFF_HOURS', '1')))
AXES_RESET_ON_SUCCESS = True                       # reset counter on good login
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_ENABLED = True
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'

AUTHENTICATION_BACKENDS = [
    # axes must be first so locked accounts are rejected before password check
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ── Django security headers (applied by SecurityMiddleware) ───────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Enable HSTS only when running behind TLS (set via env in production)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'true').lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'true').lower() in ('1', 'true', 'yes')
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'true').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'true').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'true').lower() in ('1', 'true', 'yes')

# ── Sentry error tracking ────────────────────────────────────────────────────
SENTRY_DSN = os.getenv('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv('SENTRY_ENVIRONMENT', 'production'),
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
    )

# ── Centralised security event logging (NCSS 2030 — Audit & Monitoring) ──────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'security': {
            'format': '{asctime} [SECURITY] {levelname} {name} | {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '{asctime} {levelname} {name} {process} {thread} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.getenv(
                'SECURITY_LOG_PATH',
                os.path.join(BASE_DIR, 'logs', 'security.log'),
            ),
            'maxBytes': 10 * 1024 * 1024,   # 10 MB
            'backupCount': 10,
            'formatter': 'security',
            'delay': True,
        },
        'app_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
            'delay': True,
        },
        'celery_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'celery.log'),
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'json',
            'delay': True,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'app_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'axes': {
            'handlers': ['console', 'security_file', 'app_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'scdms.security': {
            'handlers': ['console', 'security_file', 'app_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file', 'app_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file'] if not _ON_RENDER else ['console'],
            'level': os.getenv('CELERY_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'health_check': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080',
    ).split(',')
    if o.strip()
]

# FRONTEND_URL is a single canonical origin for the React SPA.
# Always include it in CORS so setting one env var is enough on Render / any host.
_frontend_url = os.getenv('FRONTEND_URL', '').strip().rstrip('/')
if _frontend_url and _frontend_url not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_frontend_url)

# CDP_BASE_URL is the public URL of this API server; include it too so same-origin
# admin tooling (Swagger UI, etc.) is never blocked.
_cdp_url = os.getenv('CDP_BASE_URL', '').strip().rstrip('/')
if _cdp_url and _cdp_url not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_cdp_url)

ALLOW_OPEN_REGISTRATION = os.getenv('ALLOW_OPEN_REGISTRATION', 'true').lower() in ('1', 'true', 'yes')

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# ── Notifications & 2FA ──────────────────────────────────────────────────────

# Resend (RESEND_API_KEY) or SMTP (DynamicEmailBackend). Override with EMAIL_BACKEND.
_resend_api_key = os.getenv('RESEND_API_KEY', '').strip()
_default_email_backend = (
    'tracker.resend_backend.ResendEmailBackend'
    if _resend_api_key
    else 'tracker.email_backend.DynamicEmailBackend'
)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', _default_email_backend)
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    'onboarding@resend.dev' if _resend_api_key else 'PSC Tracker <noreply@psc.gov.vu>',
)

# SMTP defaults (overridden by .env; DynamicEmailBackend also reads SMTP_* env first)
EMAIL_HOST = os.getenv('EMAIL_HOST', os.getenv('SMTP_HOST', 'localhost'))
EMAIL_PORT = int(os.getenv('EMAIL_PORT', os.getenv('SMTP_PORT', '1025')))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', os.getenv('SMTP_USER', ''))
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', os.getenv('SMTP_PASSWORD', ''))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', os.getenv('SMTP_TLS', 'false')).lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', os.getenv('SMTP_SSL', 'false')).lower() in ('1', 'true', 'yes')

# When True, the login flow requires a second factor (OTP)
TWO_FACTOR_REQUIRED = os.getenv('TWO_FACTOR_REQUIRED', 'false').lower() in ('1', 'true', 'yes')

# When True, the login page shows simulated push notification instead of manual TOTP input
DEMO_MODE = os.getenv('DEMO_MODE', 'true').lower() in ('1', 'true', 'yes')

# ── Celery distributed task queue ─────────────────────────────────────────────
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_TIMEZONE = 'Pacific/Efate'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ── AI / Claude API (replaces former Gemini integration) ─────────────────────
ANTHROPIC_API_KEY = os.getenv('ANTHROPIC_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
WHISPER_MODEL = os.getenv('WHISPER_MODEL', 'whisper-1')

# Quarto CLI (Commission Decision Register AI reports)
QUARTO_BIN = os.getenv('QUARTO_BIN', 'quarto')
QUARTO_RENDER_TIMEOUT = int(os.getenv('QUARTO_RENDER_TIMEOUT', '180'))
# Fast tier: feedback, classification, extraction (see AI_Features_List.txt)
CLAUDE_MODEL_HAIKU = os.getenv('CLAUDE_MODEL_HAIKU', 'claude-haiku-4-5-20251001')
# Quality tier: executive briefs, minutes drafting, similarity, chatbots
CLAUDE_MODEL_SONNET = os.getenv('CLAUDE_MODEL_SONNET', 'claude-sonnet-4-6')
# A3 — block draft→submitted when critical package gaps remain (set false to warn only)
AI_PACKAGE_BLOCK_SUBMIT = os.getenv('AI_PACKAGE_BLOCK_SUBMIT', 'true').lower() in (
    '1', 'true', 'yes', 'on',
)

# ── CMS integration (Case Management System) ──────────────────────────────────
# URL of the CMS backend API, e.g. https://cms.internal or http://localhost:8001
CMS_API_URL = os.getenv('CMS_API_URL', 'http://localhost:8001')
# JWT or API token the CDP uses when POSTing cases to the CMS
CMS_API_KEY = os.getenv('CMS_API_KEY', '')
# Shared secret the CMS sends back in X-CMS-Callback-Key on sign-off callbacks
CMS_CALLBACK_SECRET = os.getenv('CMS_CALLBACK_SECRET', '')
# Public base URL of this CDP server (used to build the cdp_callback_url sent to the CMS)
CDP_BASE_URL = os.getenv('CDP_BASE_URL', 'http://localhost:8000')

# Celery workers on Render cannot mount the API persistent disk; workers fetch files
# from the API over the private network when both vars are set.
INTERNAL_MEDIA_TOKEN = os.getenv('INTERNAL_MEDIA_TOKEN', '').strip()
_MEDIA_FETCH = os.getenv('MEDIA_FETCH_BASE_URL', '').strip().rstrip('/')
if _MEDIA_FETCH:
    MEDIA_FETCH_BASE_URL = _MEDIA_FETCH
elif _ON_RENDER:
    # Render private hostname for scdms-api (see render.yaml service name)
    MEDIA_FETCH_BASE_URL = os.getenv('RENDER_MEDIA_FETCH_BASE_URL', 'http://scdms-api:10000')
else:
    MEDIA_FETCH_BASE_URL = ''
