# Generated by Django 6.0.4 on 2026-05-08 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('psc_forms_summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Form categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tracker.ministry')),
            ],
            options={
                'ordering': ['ministry', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('psc_commissioner', 'PSC Commissioner'), ('psc_admin', 'PSC Admin'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer')], max_length=32)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='tracker.department')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='tracker.ministry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PSC profiles',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('form_type_code', models.CharField(blank=True, help_text='e.g. "PSC 3.6"', max_length=64)),
                ('routed_unit', models.CharField(blank=True, choices=[('odu', 'ODU'), ('hr', 'Manager HR'), ('vipam', 'VIPAM'), ('compliance', 'Compliance')], max_length=16)),
                ('current_stage', models.CharField(choices=[('received_by_psc', 'Received by PSC'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], default='received_by_psc', max_length=48)),
                ('received_at', models.DateTimeField()),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_started_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('closing_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('implementation_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('not_implemented', 'Not Implemented'), ('overdue', 'Overdue'), ('deferred_na', 'Deferred/N/A')], default='not_started', max_length=24)),
                ('implementation_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions_logged', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tracker.department')),
                ('form_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tracker.formcategory')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tracker.ministry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(choices=[('received_by_psc', 'Received by PSC'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48)),
                ('new_stage', models.CharField(choices=[('received_by_psc', 'Received by PSC'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.submission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('ministry', 'code'), name='uniq_department_code_per_ministry'),
        ),
    ]
