# Generated by Django 6.0.4 on 2026-05-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_roles_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('ordinary', 'Ordinary Sitting'), ('special', 'Special Sitting')], default='ordinary', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('psc_commissioner', 'PSC Commissioner'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer')], max_length=32),
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_placements', to='tracker.submission')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='tracker.meeting')),
            ],
            options={
                'ordering': ['sequence', 'added_at'],
                'unique_together': {('meeting', 'submission')},
            },
        ),
    ]
