# Generated by Django 6.0.4 on 2026-05-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('phishing', 'Phishing / Social Engineering'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach / Exposure'), ('malware', 'Malware / Ransomware'), ('account_compromise', 'Account Compromise'), ('policy_violation', 'Policy Violation'), ('suspicious_activity', 'Suspicious Activity'), ('system_outage', 'System Outage / DoS'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=15)),
                ('affected_systems', models.CharField(blank=True, max_length=500)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('dependency', 'Dependency Audit (pip-audit)'), ('sast', 'Static Analysis (Bandit)'), ('full', 'Full Scan')], default='full', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('dependency_results', models.JSONField(blank=True, default=list)),
                ('sast_results', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'get_latest_by': 'started_at',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('LOCKOUT', 'Account Locked'), ('UNLOCK', 'Account Unlocked'), ('CREATE', 'Create'), ('READ', 'Read / View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('SETTINGS', 'Settings Change'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA', '2FA Verification'), ('PERMISSION', 'Permission Change'), ('EXPORT', 'Export')], db_index=True, max_length=30)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', 'timestamp'], name='tracker_aud_actor_i_b666fe_idx'), models.Index(fields=['action', 'timestamp'], name='tracker_aud_action_08f052_idx')],
            },
        ),
    ]
