# Generated by Django 6.0.4 on 2026-05-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_commission_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontask',
            name='decision_type',
            field=models.CharField(blank=True, choices=[('appointment', 'Appointment'), ('discipline', 'Discipline'), ('policy_change', 'Policy change'), ('termination', 'Termination'), ('promotion', 'Promotion'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='commissiontask',
            name='legal_reference',
            field=models.CharField(blank=True, help_text='PSC Staff Manual, Act, or other legal cite (optional).', max_length=512),
        ),
        migrations.AddField(
            model_name='commissiontask',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissiontask',
            name='meeting_reference',
            field=models.CharField(blank=True, help_text='Sitting that produced the action (e.g. PSC Meeting 05/2026).', max_length=255),
        ),
        migrations.AddField(
            model_name='commissiontask',
            name='minute_reference',
            field=models.CharField(blank=True, help_text='Paragraph or item in official minutes (e.g. Item 4.2).', max_length=255),
        ),
        migrations.AddField(
            model_name='commissiontask',
            name='success_criteria',
            field=models.TextField(blank=True),
        ),
    ]
