# Generated by Django 6.0.4 on 2026-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_workflow_stage_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='OTPToken',
        ),
    ]
