# Generated by Django 6.0.4 on 2026-05-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_add_due_date_notification_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('LOCKOUT', 'Account Locked'), ('UNLOCK', 'Account Unlocked'), ('CREATE', 'Create'), ('READ', 'Read / View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('SETTINGS', 'Settings Change'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA', '2FA Verification'), ('PERMISSION', 'Permission Change'), ('EXPORT', 'Export'), ('FEEDBACK', 'Feedback Submission')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('psc_commissioner', 'PSC Commissioner'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('compliance_manager', 'Compliance Manager')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('psc_commissioner', 'PSC Commissioner'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('compliance_manager', 'Compliance Manager')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], default='draft', max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='new_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
    ]
