# Generated by Django 6.0.4 on 2026-05-11 23:19

from django.db import migrations


def disable_2fa(apps, schema_editor):
    Profile = apps.get_model("tracker", "Profile")
    Profile.objects.all().update(two_factor_enabled=False, totp_secret=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_add_formcategory_display_order'),
    ]

    operations = [
        migrations.RunPython(disable_2fa, migrations.RunPython.noop),
    ]
