# Generated by Django 6.0.4 on 2026-05-17 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from tracker.migration_utils import add_fields_if_missing


def add_minutes_timestamp_columns(apps, schema_editor):
    add_fields_if_missing(
        apps,
        schema_editor,
        "tracker",
        "Minutes",
        [
            (
                "circulated_at",
                models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text="When signed minutes were circulated to managers for task allocation.",
                ),
            ),
            (
                "minutes_due_at",
                models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text="SLA: minutes must be finalised within 3 days of the meeting.",
                ),
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_reset_form_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_minutes_timestamp_columns, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='minutes',
                    name='circulated_at',
                    field=models.DateTimeField(
                        blank=True,
                        null=True,
                        help_text='When signed minutes were circulated to managers for task allocation.',
                    ),
                ),
                migrations.AddField(
                    model_name='minutes',
                    name='minutes_due_at',
                    field=models.DateTimeField(
                        blank=True,
                        null=True,
                        help_text='SLA: minutes must be finalised within 3 days of the meeting.',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='submission',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Unit principal this submission has been assigned to by the unit manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pscform37data',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('temporary_salaried', 'Temporary Salaried Employee'), ('daily_rated', 'Daily Rated Worker'), ('contract', 'Contract Employee'), ('overdue', 'Overdue'), ('deferred_na', 'Deferred/N/A')], max_length=24),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='form_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tracker.formcategory'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='implementation_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('not_implemented', 'Not Implemented')], default='not_started', max_length=24),
        ),
    ]
