# Generated by Django 6.0.4 on 2026-05-23 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0058_emailtemplate_personalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.CharField(choices=[('preliminaries', '1. Preliminaries & Endorsements'), ('matters_arising', '2. Matters Arising'), ('discipline_compliance', '3. Discipline / Compliance'), ('health_commission', '4. Health Commission'), ('appointment', '5. Appointment / Acting Appointment'), ('direct_appointment', '6. Direct Appointment / Confirmation of Appointment'), ('extra_responsibility', '7. Extra Responsibility / Overtime Allowance / Special Skills Allowance'), ('contract', '8. Contract / Temporary Salaried Appointment'), ('temporary_salaried', '9. Temporary Salaried Appointment'), ('salary_adjustment', '10. Salary Adjustment'), ('training', '11. Long Term Training / Scholarship / Internship / Cadetship / Extension / Direct Appointment'), ('medical_claim', '12. Medical Claim'), ('partial_severance', '13. Partial Severance'), ('resignation', '14. Resignation / Retirement / Death'), ('other', '15. Other Matters')], default='other', help_text='Agenda section this item belongs to.', max_length=32),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Order within the category group.'),
        ),
        migrations.AlterField(
            model_name='odurestructurechecklist',
            name='submission',
            field=models.OneToOneField(help_text='The restructure submission this checklist belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='odu_checklist', to='tracker.submission'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pscformtype',
            name='agenda_category',
            field=models.CharField(blank=True, choices=[('preliminaries', '1. Preliminaries & Endorsements'), ('matters_arising', '2. Matters Arising'), ('discipline_compliance', '3. Discipline / Compliance'), ('health_commission', '4. Health Commission'), ('appointment', '5. Appointment / Acting Appointment'), ('direct_appointment', '6. Direct Appointment / Confirmation of Appointment'), ('extra_responsibility', '7. Extra Responsibility / Overtime Allowance / Special Skills Allowance'), ('contract', '8. Contract / Temporary Salaried Appointment'), ('temporary_salaried', '9. Temporary Salaried Appointment'), ('salary_adjustment', '10. Salary Adjustment'), ('training', '11. Long Term Training / Scholarship / Internship / Cadetship / Extension / Direct Appointment'), ('medical_claim', '12. Medical Claim'), ('partial_severance', '13. Partial Severance'), ('resignation', '14. Resignation / Retirement / Death'), ('other', '15. Other Matters')], default='other', help_text='Which PSC agenda section this form type belongs to. Used to auto-categorize agenda items when a submission is added to a meeting.', max_length=32),
        ),
        migrations.AlterField(
            model_name='restructuresubmissiondata',
            name='costing_notes',
            field=models.TextField(blank=True, help_text='Notes below the table (vacancy funding, part-year calculations, etc.).'),
        ),
        migrations.AlterField(
            model_name='restructuresubmissiondata',
            name='costing_rows',
            field=models.JSONField(blank=True, default=list, help_text='Array of position rows for the costing table (see model docstring).'),
        ),
        migrations.AlterField(
            model_name='restructuresubmissiondata',
            name='dg_endorses',
            field=models.BooleanField(blank=True, help_text='True = I support / endorse; False = I do not support.', null=True),
        ),
        migrations.AlterField(
            model_name='restructuresubmissiondata',
            name='subject_title',
            field=models.CharField(blank=True, help_text="Full subject/title of the proposal, e.g. 'Proposal to Revise the Organisation Structure …'", max_length=512),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], default='draft', max_length=48),
        ),
        migrations.AlterField(
            model_name='submission',
            name='routed_unit',
            field=models.CharField(blank=True, choices=[('odu', 'ODU'), ('hr', 'Manager HR'), ('vipam', 'VIPAM'), ('compliance', 'Compliance'), ('csu', 'Corporate Services Unit')], max_length=16),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='new_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
    ]
