# Generated by Django 6.0.5 on 2026-05-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0091_agenda_category_dynamic_sections'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailybriefdeliverylog',
            new_name='tracker_dai_created_788b6d_idx',
            old_name='tracker_dai_created_6e0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='dailybriefdeliverylog',
            new_name='tracker_dai_brief_t_6ee3d1_idx',
            old_name='tracker_dai_brief_t_8c8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='sittingpacksession',
            new_name='tracker_sit_meeting_c8f353_idx',
            old_name='tracker_sit_meeting_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='submissionpresence',
            new_name='tracker_sub_submiss_6e2e39_idx',
            old_name='tracker_sub_submiss_4c8e21_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('LOCKOUT', 'Account Locked'), ('UNLOCK', 'Account Unlocked'), ('CREATE', 'Create'), ('READ', 'Read / View'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('DOWNLOAD', 'Download'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore'), ('SETTINGS', 'Settings Change'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA', '2FA Verification'), ('PERMISSION', 'Permission Change'), ('EXPORT', 'Export'), ('FEEDBACK', 'Feedback Submission'), ('DECISION', 'Decision / Stage Proof')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dailybriefsettings',
            name='delivery_hour',
            field=models.PositiveSmallIntegerField(default=7, help_text='Hour (05–12) in Pacific/Efate when briefs are sent.'),
        ),
        migrations.AlterField(
            model_name='dailybriefsettings',
            name='manager_recipient_ids',
            field=models.JSONField(blank=True, default=list, help_text='Legacy/extra manager recipient user IDs (synced with M2M on save).'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=32),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='form_type',
            field=models.ForeignKey(blank=True, help_text='When set, applies only to submissions of this specific form type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='tracker.pscformtype'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='mandatory_for_stage',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], help_text='Block transition FROM this stage if this item is incomplete.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ai_clarification_bilingual',
            field=models.JSONField(blank=True, default=dict, help_text='English + Bislama clarification text for ministry (returned for clarification).'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], default='draft', max_length=48),
        ),
        migrations.AlterField(
            model_name='submissiondocument',
            name='ai_annotation_suggestions',
            field=models.JSONField(blank=True, default=dict, help_text='AI-suggested PDF review highlights (verify before applying).'),
        ),
        migrations.AlterField(
            model_name='submissiondocument',
            name='ai_redaction_spans',
            field=models.JSONField(blank=True, default=dict, help_text='E3 suggested redaction spans (human approves).'),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='new_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report')], max_length=48),
        ),
    ]
