# Generated by Django 6.0.5 on 2026-06-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0108_submission_assigned_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendasection',
            name='receiver_roles',
            field=models.JSONField(blank=True, default=list, help_text='PSC profile roles allowed to receive new submissions for this agenda section. Empty means fallback to routed unit manager only.'),
        ),
    ]
