# Generated by Django 6.0.5 on 2026-06-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0109_checklist_response_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pscformtype',
            name='checklist_form_type',
            field=models.ForeignKey(blank=True, help_text='Checklist form type attached to this submission form type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_form_types', to='tracker.pscformtype'),
        ),
        migrations.AddField(
            model_name='pscformtype',
            name='is_checklist',
            field=models.BooleanField(default=False, help_text='True when this form type defines a checklist (not a submission form).'),
        ),
        migrations.CreateModel(
            name='SubmissionChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text="Keyed by PSCFormField.field_key — stores the principal's answers.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for manager review'), ('approved', 'Approved by manager'), ('returned', 'Returned for revision')], db_index=True, default='draft', max_length=12)),
                ('manager_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_form_type', models.ForeignKey(limit_choices_to={'is_checklist': True}, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to='tracker.pscformtype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses_created', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='tracker.submission')),
            ],
            options={
                'verbose_name': 'Submission Checklist Response',
                'verbose_name_plural': 'Submission Checklist Responses',
                'ordering': ['-created_at'],
                'unique_together': {('submission', 'checklist_form_type')},
            },
        ),
    ]
