# Generated by Django 6.0.5 on 2026-06-01 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0110_checklist_pscformtype_and_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checklist_review_deadline_at',
            field=models.DateTimeField(blank=True, help_text='SLA deadline for checklist review (configurable working days).', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='checklist_review_started_at',
            field=models.DateTimeField(blank=True, help_text='When this submission entered Manager Checklist Review.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='recalled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recalled_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='recalled_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='mandatory_for_stage',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], help_text='Block transition FROM this stage if this item is incomplete.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], default='draft', max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='new_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], max_length=48),
        ),
    ]
