# Generated by Django 6.0.5 on 2026-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0111_workflow_improvements_recalled_sla'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='pscformtype',
            name='assessment_deadline_days',
            field=models.PositiveSmallIntegerField(default=21, help_text='Working-day assessment deadline for this form type (default 21). Set lower for routine forms, higher for complex matters.'),
        ),
        migrations.AddField(
            model_name='pscformtype',
            name='routed_unit',
            field=models.CharField(blank=True, default='', help_text='OPSC unit this form type routes to for checklist review. Leave blank if no auto-routing is needed.', max_length=16),
        ),
    ]
