# Generated by Django 6.0.5 on 2026-06-01 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0113_celery_beat_escalation_autoscheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary responsible principal assigned by the unit manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubmissionCoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('secondary', 'Secondary analyst'), ('specialist', 'Specialist reviewer')], default='secondary', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_assignment_records', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_assignments', to='tracker.submission')),
            ],
            options={
                'verbose_name': 'Co-Assignment',
                'verbose_name_plural': 'Co-Assignments',
                'ordering': ['assigned_at'],
                'unique_together': {('submission', 'principal')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='co_assigned_principals',
            field=models.ManyToManyField(blank=True, related_name='co_assigned_submissions', through='tracker.SubmissionCoAssignment', through_fields=('submission', 'principal'), to=settings.AUTH_USER_MODEL),
        ),
    ]
