# Generated by Django 6.0.5 on 2026-06-04 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0123_workflow_chain_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_family', models.CharField(choices=[('employee_disciplinary', 'Employee Internal Disciplinary'), ('serious_misconduct_employee', 'Serious Misconduct — Employee'), ('temporary_suspension', 'Temporary Suspension'), ('grievance', 'Grievance Process'), ('senior_serious_misconduct', 'Senior Executive — Serious Misconduct'), ('senior_poor_performance', 'Senior Executive — Poor Performance'), ('policy_review', 'Policy / PSA Amendment')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('subject_name', models.CharField(max_length=200)),
                ('subject_position', models.CharField(blank=True, max_length=200)),
                ('subject_ministry', models.CharField(blank=True, max_length=200)),
                ('is_senior_executive', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_case', to='tracker.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('subject_name', models.CharField(blank=True, max_length=200)),
                ('subject_position', models.CharField(blank=True, max_length=200)),
                ('subject_ministry', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted to Case')], default='received', max_length=20)),
                ('closed_reason', models.TextField(blank=True, help_text='Reason shown to the lodging ministry if rejected/closed.')),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lodged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodged_complaints', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tracker.ministry')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triaged_complaints', to=settings.AUTH_USER_MODEL)),
                ('compliance_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_complaints', to='tracker.compliancecase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='tracker.compliancecase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LitigationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('legal_counsel', models.CharField(blank=True, max_length=200)),
                ('court_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('settled', 'Settled'), ('closed', 'Closed'), ('appealed', 'Appealed')], default='active', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_initiated', models.DateField(default=django.utils.timezone.now)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigation_records', to='tracker.compliancecase')),
            ],
            options={
                'ordering': ['-date_initiated'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150)),
                ('stage_code', models.CharField(blank=True, max_length=60)),
                ('stage_order', models.PositiveSmallIntegerField()),
                ('responsible_role', models.CharField(blank=True, max_length=40)),
                ('statutory_ref', models.CharField(blank=True, max_length=100)),
                ('sla_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sla_working_days', models.BooleanField(default=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sla_status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('is_optional', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tracker.compliancecase')),
            ],
            options={
                'ordering': ['stage_order'],
                'unique_together': {('case', 'stage_order')},
            },
        ),
    ]
