# Generated by Django 6.0.5 on 2026-06-04 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0124_compliancecase_complaint_casenote_litigationrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancecase',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='litigationrecord',
            name='date_initiated',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
