# Generated by Django 6.0.5 on 2026-06-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0125_alter_compliancecase_date_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='cms_case_closed_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cms_case_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cms_case_reference',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cms_dispatched_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cms_signoff_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cms_signoff_outcome',
        ),
    ]
