import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

BEAT_NAME = "generate-quarterly-implementation-report"


def register_beat(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    quarterly, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="6",
        day_of_month="1", month_of_year="1,4,7,10", day_of_week="*",
        timezone="Pacific/Efate",
    )
    PeriodicTask.objects.update_or_create(
        name=BEAT_NAME,
        defaults={
            "crontab": quarterly,
            "task": "tracker.tasks.generate_quarterly_implementation_report",
            "enabled": True,
        },
    )


def deregister_beat(apps, schema_editor):
    apps.get_model("django_celery_beat", "PeriodicTask").objects.filter(
        name=BEAT_NAME
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0147_implementation_rollup_timestamps"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementationDashboardReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(help_text='Period label, e.g. "Q1 2026".', max_length=64)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("target_days", models.PositiveIntegerField(default=30, help_text="IMPLEMENTATION_TARGET_DAYS in effect when generated.")),
                ("summary", models.JSONField(blank=True, default=dict, help_text="Snapshot of the overall KPI block at generation time.")),
                ("pdf_file", models.FileField(blank=True, upload_to="implementation_reports/%Y/%m/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("requested_by", models.ForeignKey(blank=True, help_text="Null when generated by the quarterly schedule.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="implementation_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(register_beat, deregister_beat),
    ]
