import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

BEAT_NAME = "generate-annual-report-statistics"


def register_beat(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    yearly_jan15, _ = CrontabSchedule.objects.get_or_create(
        minute="0", hour="6",
        day_of_month="15", month_of_year="1", day_of_week="*",
        timezone="Pacific/Efate",
    )
    PeriodicTask.objects.update_or_create(
        name=BEAT_NAME,
        defaults={
            "crontab": yearly_jan15,
            "task": "tracker.tasks.generate_annual_report_statistics",
            "enabled": True,
        },
    )


def deregister_beat(apps, schema_editor):
    apps.get_model("django_celery_beat", "PeriodicTask").objects.filter(
        name=BEAT_NAME
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0150_decision_service"),
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("dataset", models.JSONField(blank=True, default=dict, help_text="Frozen statistics dataset behind the PDF.")),
                ("pdf_file", models.FileField(blank=True, upload_to="annual_reports/%Y/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("requested_by", models.ForeignKey(blank=True, help_text="Null when generated by the yearly schedule.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="annual_reports", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(register_beat, deregister_beat),
    ]
