# Generated by Django 6.0.6 on 2026-06-15 04:56

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0155_unit_scoped_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='submission',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda_approved_by',
            field=models.ForeignKey(blank=True, help_text='Chairperson who endorsed the agenda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
