# Generated by Django 6.0.6 on 2026-06-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0158_fr11_grievance_mediator_fr13_litigation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('principal_org_dev_analyst', 'Principal Organization Development Analyst'), ('principal_job_analyst', 'Principal Job Analyst'), ('compliance_principal', 'Compliance Principal'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('principal_org_dev_analyst', 'Principal Organization Development Analyst'), ('principal_job_analyst', 'Principal Job Analyst'), ('compliance_principal', 'Compliance Principal'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member')], max_length=50, unique=True),
        ),
    ]
