# Generated by Django 6.0.6 on 2026-06-17 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0161_merge_fr09_seed_odu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda_adopted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda_adopted_by',
            field=models.ForeignKey(blank=True, help_text='Chairperson who adopted the agenda at the start of the sitting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_adopted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='signed_document',
            field=models.FileField(blank=True, help_text='Scanned copy of the manually (wet-ink) signed minutes.', null=True, upload_to='minutes/signed/'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='signed_uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Senior Admin Officer who uploaded the scanned signed minutes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signed_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissiontask',
            name='decision_outcome',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('deferred_next', 'Deferred To Next Meeting'), ('deferred_info', 'Deferred — Need more information')], max_length=32),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='pdf_version',
            field=models.FileField(blank=True, help_text='Generated (unsigned) PDF used for printing and for digital signing.', null=True, upload_to='minutes/'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='mandatory_for_stage',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('dg_approved', 'Endorsed by DG — Pending HR Submission'), ('pending_manager_approval', 'Pending Manager Approval'), ('pending_second_approval', 'Pending Second Approval'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('pending_secretary_approval', 'Pending Secretary Approval'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], help_text='Block transition FROM this stage if this item is incomplete.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('dg_approved', 'Endorsed by DG — Pending HR Submission'), ('pending_manager_approval', 'Pending Manager Approval'), ('pending_second_approval', 'Pending Second Approval'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('pending_secretary_approval', 'Pending Secretary Approval'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], default='draft', max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='new_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('dg_approved', 'Endorsed by DG — Pending HR Submission'), ('pending_manager_approval', 'Pending Manager Approval'), ('pending_second_approval', 'Pending Second Approval'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('pending_secretary_approval', 'Pending Secretary Approval'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], max_length=48),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='previous_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('dg_approved', 'Endorsed by DG — Pending HR Submission'), ('pending_manager_approval', 'Pending Manager Approval'), ('pending_second_approval', 'Pending Second Approval'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('pending_secretary_approval', 'Pending Secretary Approval'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], max_length=48),
        ),
        migrations.CreateModel(
            name='MeetingOtherMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('detail', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('decision_text', models.TextField(blank=True, help_text='Outcome/decision recorded for this item during the sitting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_matters', to='tracker.meeting')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_other_matters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence', 'created_at'],
            },
        ),
    ]
