# Generated by Django 6.0.6 on 2026-06-18 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0162_commission_sitting_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, help_text='The prepared (unsigned) letter, generated or uploaded for printing.', null=True, upload_to='decision_letters/%Y/%m/')),
                ('signed_scan', models.FileField(blank=True, help_text='Optional scan of the wet-ink signed letter, for the record.', null=True, upload_to='decision_letters/signed/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('printed', 'Printed'), ('signed', 'Signed by Secretary'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up')], default='draft', max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_notified_at', models.DateTimeField(blank=True, help_text='When the originating ministry HR was notified the letter is ready.', null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_letters', to='tracker.commissiontask')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_decision_letters', to=settings.AUTH_USER_MODEL)),
                ('picked_up_by', models.ForeignKey(blank=True, help_text='Ministry HR who confirmed physical collection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_decision_letters', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, help_text='Action officer (principal/senior) who prepared the letter.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_decision_letters', to=settings.AUTH_USER_MODEL)),
                ('signed_by', models.ForeignKey(blank=True, help_text='Secretary who signed the letter (wet-ink record).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_decision_letters', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, help_text='Convenience link (derived from the task) for ministry/HR lookup.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_letters', to='tracker.submission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendaDeferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferral_type', models.CharField(choices=[('to_next_meeting', 'Deferred to Next Meeting'), ('push_to_next', 'Moved to Next Meeting (pre-sitting)'), ('back_to_unit', 'Deferred Back to Unit'), ('back_to_hr', 'Deferred Back to HR'), ('on_hold', 'Deferred (on hold)')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('deferred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='True once the deferred item has been decided or re-tabled and concluded.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferrals', to='tracker.agendaitem')),
                ('deferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_deferrals_made', to=settings.AUTH_USER_MODEL)),
                ('from_meeting', models.ForeignKey(blank=True, help_text='The sitting the item was deferred from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferrals_out', to='tracker.meeting')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_deferrals', to='tracker.submission')),
                ('to_meeting', models.ForeignKey(blank=True, help_text='The sitting the item was carried to (null for back-to-unit/HR/on-hold).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferrals_in', to='tracker.meeting')),
            ],
            options={
                'ordering': ['-deferred_at'],
                'indexes': [models.Index(fields=['resolved', 'deferral_type'], name='tracker_age_resolve_23074b_idx'), models.Index(fields=['submission', 'resolved'], name='tracker_age_submiss_a3d764_idx')],
            },
        ),
    ]
