# Generated by Django 6.0.6 on 2026-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0163_decisionletter_agendadeferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push',
            field=models.BooleanField(default=False, help_text='Send a mobile/desktop web-push for this notification (important events only).'),
        ),
    ]
