# Generated by Django 6.0.6 on 2026-06-18 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0164_notification_push'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('minor', 'Minor / Disciplinary Offence'), ('serious_misconduct', 'Serious Misconduct (Appendix C)')], default='minor', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('statutory_ref', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='compliancecase',
            name='offence_detail',
            field=models.TextField(blank=True, help_text='Free-text particulars of the offence, if needed.'),
        ),
        migrations.AddField(
            model_name='litigationrecord',
            name='court_date_notified',
            field=models.DateField(blank=True, help_text='The next_court_date value a reminder was last sent for (dedupe guard).', null=True),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_members_text', models.CharField(blank=True, help_text='Free-text panel names for external members not in the system.', max_length=500)),
                ('terms_of_reference', models.TextField(blank=True)),
                ('appointed_at', models.DateField(blank=True, null=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='compliance/investigations/%Y/%m/')),
                ('status', models.CharField(choices=[('appointed', 'Panel Appointed'), ('in_progress', 'Investigation In Progress'), ('reported', 'Report Submitted'), ('closed', 'Closed')], default='appointed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to='tracker.compliancecase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations_created', to=settings.AUTH_USER_MODEL)),
                ('panel_members', models.ManyToManyField(blank=True, help_text='Appointed panel / investigator (typically users with the Panel Member role).', related_name='investigation_panels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compliancecase',
            name='nature_of_offence',
            field=models.ForeignKey(blank=True, help_text='Catalogued nature of the offence (drives repeat-offence escalation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='tracker.offencetype'),
        ),
        migrations.CreateModel(
            name='SuspensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_basis', models.CharField(choices=[('full', 'Full Salary'), ('half', 'Half Salary (temporary suspension)'), ('no_pay', 'Without Pay (PSDB sanction)')], default='half', max_length=10)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('withheld_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Salary withheld during suspension (e.g. the half not paid).', max_digits=12, null=True)),
                ('reimbursed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suspension_start', models.DateField()),
                ('suspension_end', models.DateField(blank=True, help_text='Expiry of the suspension (temporary suspension max 2 months).', null=True)),
                ('max_period_days', models.PositiveSmallIntegerField(default=60, help_text='Statutory cap (60 days ≈ 2 months for temporary suspension).')),
                ('reimbursement_status', models.CharField(choices=[('pending', 'Pending OPSC Assessment'), ('reimburse', 'Reimburse Withheld Salary'), ('forfeit', 'Forfeit Withheld Salary'), ('na', 'Not Applicable')], default='pending', help_text='OPSC assessment of whether withheld salary is reimbursed on reinstatement.', max_length=12)),
                ('opsc_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('reinstated_at', models.DateField(blank=True, null=True)),
                ('reinstated_on_full_salary', models.BooleanField(default=False, help_text='True once deemed reinstated on full salary at expiry of the suspension.')),
                ('expiry_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='tracker.compliancecase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_created', to=settings.AUTH_USER_MODEL)),
                ('opsc_assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspension_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-suspension_start'],
            },
        ),
    ]
