# Generated by Django 6.0.6 on 2026-06-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0167_compliancestagedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecasestage',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='compliancecasestage',
            name='responsible_officer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='submissiondocument',
            name='note',
            field=models.TextField(blank=True, help_text='Free-text note about this document (e.g. compliance evidence note).'),
        ),
    ]
