# Generated by Django 6.0.7 on 2026-07-21 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0173_seed_meeting_scheduled_email_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, help_text='Free-text unit label shown on the response, e.g. VIPAM / HR / ODU.', max_length=120)),
                ('section_id', models.CharField(max_length=16)),
                ('section_title', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=24)),
                ('item_text', models.TextField()),
                ('rating', models.CharField(blank=True, choices=[('good', 'Works well'), ('needs', 'Needs work'), ('missing', 'Missing / N/A')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback_checklist/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_checklist_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Checklist Response',
                'ordering': ['user_id', 'section_id', 'item_id'],
                'unique_together': {('user', 'item_id')},
            },
        ),
    ]
