# Generated by Django 6.0.7 on 2026-07-21 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0174_feedback_checklist_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='pscformtype',
            name='approval_chain',
            field=models.JSONField(blank=True, default=list, help_text='Ordered approval steps required for a submission of this form type when it is attached to a parent submission (is_attachment=True). Each step: {"stage": "pending_manager_approval", "roles": ["odu_manager"], "label": "ODU Manager Approval"}. Stages: pending_manager_approval, pending_second_approval. Only used for attachment forms.'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='required_form',
            field=models.ForeignKey(blank=True, help_text="When set, this requirement is satisfied by attaching a submission of this form type (parent_submission + is_attachment=True) rather than a plain file. The creation flow proposes adding it; it is marked present once the attached submission's own approval chain reaches Approved.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_by_documents', to='tracker.pscformtype'),
        ),
    ]
