# Generated by Django 6.0.7 on 2026-07-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0176_seed_psc_2_2_attachment_pilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('pending_dg_endorsement', 'Submitted to DG (Pending Endorsement)'), ('dg_approved', 'Endorsed by DG — Pending HR Submission'), ('pending_manager_approval', 'Pending Manager Approval'), ('pending_second_approval', 'Pending Second Approval'), ('submitted', 'Submitted to PSC'), ('received_by_psc', 'Received by PSC'), ('returned_for_clarification', 'Returned for Clarification'), ('registered_routed', 'Registered and Routed'), ('manager_checklist_review', 'Manager Checklist Review'), ('under_assessment', 'Under Assessment'), ('pending_secretary_approval', 'Pending Secretary Approval'), ('compliance_under_review', 'Compliance Under Review (CMS)'), ('deferred', 'Deferred'), ('tabled', 'Tabled'), ('awaiting_legal_advice', 'Awaiting Legal Advice'), ('awaiting_cabinet_decision', 'Awaiting Cabinet Decision'), ('resubmitted', 'Resubmitted'), ('forwarded_to_commission', 'Forwarded to Commission'), ('commission_sitting', 'Commission Sitting'), ('matters_arising', 'Matters Arising'), ('approved', 'Approved'), ('noted', 'Noted'), ('not_approved', 'Not Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('deferred_back_to_hr', 'Deferred Back to HR'), ('deferred_back_to_unit', 'Deferred Back to Unit'), ('secretary_review', 'Secretary Review'), ('minutes_drafted_signed', 'Minutes Drafted and Signed'), ('decision_entered_assigned', 'Decision Entered and Assigned'), ('under_implementation', 'Under Implementation'), ('implementation_report', 'Implementation Report'), ('recalled', 'Recalled by Ministry')], max_length=48)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='tracker.submission')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
