# Generated by Django 6.0.7 on 2026-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0177_submissionstageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='notify_emails',
            field=models.JSONField(blank=True, default=list, help_text='Extra email addresses (no SCDMS account required) to notify when this submission reaches PSC, so they can track its progress via reference number.'),
        ),
    ]
