# Generated by Django 6.0.7 on 2026-07-21 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0179_seed_submission_received_confirmation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsignature',
            name='auth_method',
            field=models.CharField(blank=True, help_text='How the signing session was authenticated: totp, pin, password_only, or push_demo.', max_length=16),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='trusted_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.trustedsession'),
        ),
        migrations.AddField(
            model_name='flyingminutesignature',
            name='auth_method',
            field=models.CharField(blank=True, help_text='How the signing session was authenticated: totp, pin, password_only, or push_demo.', max_length=16),
        ),
        migrations.AddField(
            model_name='flyingminutesignature',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flyingminutesignature',
            name='trusted_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.trustedsession'),
        ),
        migrations.AddField(
            model_name='formsectionsignature',
            name='auth_method',
            field=models.CharField(blank=True, help_text='How the signing session was authenticated: totp, pin, password_only, or push_demo.', max_length=16),
        ),
        migrations.AddField(
            model_name='formsectionsignature',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsectionsignature',
            name='trusted_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracker.trustedsession'),
        ),
    ]
