# Generated by Django 6.0.7 on 2026-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0188_restore_internal_form_types_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='expected_document_type',
            field=models.CharField(blank=True, choices=[('unclassified', 'Unclassified'), ('appointment_letter', 'Appointment letter'), ('medical_certificate', 'Medical certificate'), ('psc_form', 'PSC form'), ('position_description', 'Position description'), ('dg_endorsement', 'DG / HoA endorsement'), ('organisational_chart', 'Organisational chart'), ('legislation_policy', 'Legislation / policy'), ('financial_costing', 'Financial / costing'), ('correspondence', 'Correspondence'), ('supporting_evidence', 'Supporting evidence'), ('minutes_report', 'Minutes / report'), ('other', 'Other')], default='', help_text="When set, an uploaded file's classified document type is checked against this expectation; a confident mismatch un-ticks the checklist item instead of trusting any attached file. Leave blank to skip content validation for this item.", max_length=32),
        ),
        migrations.AddField(
            model_name='submissionchecklistitem',
            name='content_mismatch',
            field=models.BooleanField(default=False, help_text="Set by the content-validation check when an uploaded file's classified type doesn't match document.expected_document_type. Cleared automatically on manual officer toggle."),
        ),
    ]
