# Generated by Django 6.0.7 on 2026-08-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0189_required_document_content_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='follows_normal_route',
            field=models.BooleanField(default=False, help_text="For an internal submission (is_internal=True): still route it through the normal PSC workflow — responsible unit checklist, assessment, Secretary approval gate, Commission — instead of the short internal-only path straight to the Secretary. Used by CSU Manager submissions (e.g. appointment of OPSC staff), which stay PSC-staff-only visible but still require the responsible unit's checklist review like any other case."),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True when submitted by OPSC staff (CSU/VIPAM/Compliance) — PSC-staff-only visible.'),
        ),
    ]
