# Generated by Django 6.0.7 on 2026-08-04 23:40
#
# CSU Manager now uses the same submission-type catalog as the HR Unit (see
# Submission.follows_normal_route, migration 0190) instead of a dedicated
# "Internal Submissions" catalog. VIPAM has its own separate types (training/
# scholarship, under the "training" FormCategory) and is unaffected. Removes
# the now-unused INT-1..INT-8 PSCFormType rows and their FormCategory.
#
# One pre-existing, unrelated submission (id=14, "Resignation for Mr. Edwin
# Frank — MOIA") has form_type_code="INT-2" as a loose string value (not a FK),
# under a different, real form_category ("14. Resignation / Retirement /
# Death") — it is not part of the Internal Submissions catalog being removed
# here and is left untouched; it will fall back to category-level checklist
# matching instead of form-type-specific matching.

from django.db import migrations

INT_CODES = ["INT-1", "INT-2", "INT-3", "INT-4", "INT-5", "INT-6", "INT-7", "INT-8"]


def remove_internal_form_types(apps, schema_editor):
    PSCFormType = apps.get_model("tracker", "PSCFormType")
    FormCategory = apps.get_model("tracker", "FormCategory")

    PSCFormType.objects.filter(code__in=INT_CODES).delete()
    FormCategory.objects.filter(code="INTERNAL").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0190_add_submission_follows_normal_route'),
    ]

    operations = [
        migrations.RunPython(remove_internal_form_types, migrations.RunPython.noop),
    ]
