# Generated by Django 6.0.7 on 2026-08-05 00:46

from django.db import migrations, models


def seed_ready_for_manager_template(apps, schema_editor):
    from tracker.email_templates import seed_default_email_templates

    seed_default_email_templates()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0192_meeting_postponed_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ready_for_manager_at',
            field=models.DateTimeField(blank=True, help_text='Set when the assigned principal/senior officer submits their completed checklist review or assessment back to the unit manager. The manager — not the assignee — is the one who advances the workflow stage from here. Cleared when reassigned or once the manager advances the stage.', null=True),
        ),
        migrations.RunPython(seed_ready_for_manager_template, migrations.RunPython.noop),
    ]
