# Generated by Django 6.0.7 on 2026-08-05 02:30

from django.db import migrations, models


def seed_letter_templates(apps, schema_editor):
    from tracker.letter_templates import seed_default_letter_templates

    seed_default_letter_templates()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0193_unit_worker_handback_to_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type_code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('recruitment', 'Recruitment & Selection'), ('cessation', 'Cessation of Employment'), ('secondment', 'Secondment'), ('leave_payout', 'Leave Payout'), ('allowances', 'Allowances & Claims')], default='recruitment', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('placeholders', models.TextField(blank=True, help_text='Comma-separated placeholder names available in subject/body.')),
                ('subject_template', models.CharField(max_length=255)),
                ('body_text_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates can be reset to defaults but not deleted.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RunPython(seed_letter_templates, migrations.RunPython.noop),
    ]
