# Generated by Django 6.0.7 on 2026-08-06 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0196_simplify_meeting_header_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODURestructureBoardPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_number', models.CharField(blank=True, max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.CharField(blank=True, default='Secretary', max_length=255)),
                ('action_officer', models.CharField(blank=True, max_length=255)),
                ('psc_file', models.CharField(blank=True, max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('date_submitted_to_psc_by_ministry', models.DateField(blank=True, null=True)),
                ('date_submitted_to_pscb', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('background', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('discussions', models.TextField(blank=True)),
                ('odu_assessment', models.TextField(blank=True)),
                ('costing_rows', models.JSONField(blank=True, default=list)),
                ('costing_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odu_board_papers_created', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='The restructure submission this board paper belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='odu_board_paper', to='tracker.submission')),
            ],
            options={
                'verbose_name': 'ODU Restructure Board Paper',
                'verbose_name_plural': 'ODU Restructure Board Papers',
                'ordering': ['-created_at'],
            },
        ),
    ]
