# Generated by Django 6.0.7 on 2026-08-06 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0197_add_odu_restructure_board_paper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odu_board_papers_manager_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='secretary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='secretary_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odu_board_papers_secretary_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Manager ODU'), ('manager_approved', 'Approved by Manager ODU — Pending Secretary'), ('secretary_approved', 'Approved by Secretary')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odurestructureboardpaper',
            name='submitted_for_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odu_board_papers_submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
