# Generated by Django 6.0.8 on 2026-08-14 03:59
# Manually reordered: AlterUniqueTogether must run before the RemoveField
# operations that drop fields referenced by those constraints, otherwise
# Django can't resolve the column to drop the composed index (FieldDoesNotExist).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0232_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compliancecasestage',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='compliancestagedocument',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='compliance_case',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lodged_by',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ministry',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='triaged_by',
        ),
        migrations.RemoveField(
            model_name='compliancecase',
            name='nature_of_offence',
        ),
        migrations.RemoveField(
            model_name='compliancecase',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='case',
        ),
        migrations.RemoveField(
            model_name='compliancecasestage',
            name='case',
        ),
        migrations.RemoveField(
            model_name='grievancemediatorappointment',
            name='case',
        ),
        migrations.RemoveField(
            model_name='compliancecasedecision',
            name='case',
        ),
        migrations.RemoveField(
            model_name='suspensionrecord',
            name='case',
        ),
        migrations.RemoveField(
            model_name='litigationrecord',
            name='case',
        ),
        migrations.RemoveField(
            model_name='compliancecasedecision',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='compliancestagedocument',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='compliancestagedocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='compliancestagedocument',
            name='linked_by',
        ),
        migrations.RemoveField(
            model_name='grievancemediatorappointment',
            name='appointed_by',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='panel_members',
        ),
        migrations.RemoveField(
            model_name='suspensionrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='suspensionrecord',
            name='opsc_assessed_by',
        ),
        migrations.DeleteModel(
            name='CaseNote',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='OffenceType',
        ),
        migrations.DeleteModel(
            name='ComplianceCase',
        ),
        migrations.DeleteModel(
            name='LitigationRecord',
        ),
        migrations.DeleteModel(
            name='ComplianceCaseDecision',
        ),
        migrations.DeleteModel(
            name='ComplianceCaseStage',
        ),
        migrations.DeleteModel(
            name='ComplianceStageDocument',
        ),
        migrations.DeleteModel(
            name='GrievanceMediatorAppointment',
        ),
        migrations.DeleteModel(
            name='Investigation',
        ),
        migrations.DeleteModel(
            name='SuspensionRecord',
        ),
    ]
