# Generated by Django 6.0.8 on 2026-08-16 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0236_reseed_compliance_form_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['current_stage', '-received_at'], name='submission_stage_received_idx'),
        ),
    ]
