# Generated by Django 6.0.8 on 2026-08-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0237_submission_stage_received_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('retrying', 'Transient failure — retrying'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('error_detail', models.TextField(blank=True)),
                ('model_tier', models.CharField(blank=True, max_length=16)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_logs', to='tracker.submission')),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='tracker_aig_feature_6d2bf1_idx'), models.Index(fields=['status', 'created_at'], name='tracker_aig_status_c44810_idx')],
            },
        ),
    ]
