# Generated by Django 6.0.8 on 2026-08-16 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0238_ai_generation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(db_index=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_flags', to='tracker.submission')),
            ],
            options={
                'verbose_name': 'Integrity Flag',
                'verbose_name_plural': 'Integrity Flags',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['check_name', 'resolved_at'], name='tracker_int_check_n_8fdcba_idx')],
            },
        ),
    ]
