# Generated by Django 6.0.8 on 2026-08-19 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ipdu_manager role, ipdu RoutedUnit, and the IPDUBoardPaper model."""

    dependencies = [
        ('tracker', '0239_integrity_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('ipdu_manager', 'Manager IPDU'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal'), ('vipam_senior', 'VIPAM Senior Officer'), ('hr_unit_senior', 'HR Unit Senior Officer'), ('odu_senior', 'ODU Senior Officer'), ('csu_senior', 'CSU Senior Officer'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('ipdu_manager', 'Manager IPDU'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal'), ('vipam_senior', 'VIPAM Senior Officer'), ('hr_unit_senior', 'HR Unit Senior Officer'), ('odu_senior', 'ODU Senior Officer'), ('csu_senior', 'CSU Senior Officer'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='routed_unit',
            field=models.CharField(blank=True, choices=[('odu', 'ODU'), ('hr', 'Manager HR'), ('vipam', 'VIPAM'), ('compliance', 'Compliance'), ('csu', 'Corporate Services Unit'), ('ipdu', 'IPDU')], max_length=16),
        ),
        migrations.AlterField(
            model_name='unit',
            name='routed_unit',
            field=models.CharField(blank=True, choices=[('odu', 'ODU'), ('hr', 'Manager HR'), ('vipam', 'VIPAM'), ('compliance', 'Compliance'), ('csu', 'Corporate Services Unit'), ('ipdu', 'IPDU')], help_text='OPSC workflow routing key when submissions are routed to this unit.', max_length=16),
        ),
        migrations.CreateModel(
            name='IPDUBoardPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Manager ODU'), ('manager_approved', 'Approved by Manager ODU — Pending Secretary'), ('secretary_approved', 'Approved by Secretary')], db_index=True, default='draft', max_length=20)),
                ('submitted_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('secretary_approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_note', models.TextField(blank=True, help_text="Secretary's note on what needs changing, from the last return.")),
                ('meeting_number', models.CharField(blank=True, max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.CharField(blank=True, default='Secretary', max_length=255)),
                ('action_officer', models.CharField(blank=True, max_length=255)),
                ('psc_file', models.CharField(blank=True, max_length=255)),
                ('prepared_by', models.CharField(blank=True, max_length=255)),
                ('date_submitted_to_psc_by_ministry', models.DateField(blank=True, null=True)),
                ('date_submitted_to_pscb', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('background', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('discussions', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('deliverable_rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ipdu_board_papers_created', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, help_text='Secretary who last sent this back to Manager IPDU for changes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipdu_board_papers_returned', to=settings.AUTH_USER_MODEL)),
                ('secretary_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipdu_board_papers_secretary_approved', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(help_text='The IPDU submission this board paper belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='ipdu_board_paper', to='tracker.submission')),
                ('submitted_for_review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipdu_board_papers_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPDU Board Paper',
                'verbose_name_plural': 'IPDU Board Papers',
                'ordering': ['-created_at'],
            },
        ),
    ]
