# Generated by Django 6.0.8 on 2026-08-19 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0242_agenda_item_form_type_grouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipduboardpaper',
            name='date_submitted_to_psc_by_ministry',
        ),
        migrations.RemoveField(
            model_name='ipduboardpaper',
            name='date_submitted_to_pscb',
        ),
        migrations.RemoveField(
            model_name='ipduboardpaper',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='ipduboardpaper',
            name='meeting_number',
        ),
        migrations.RemoveField(
            model_name='ipduboardpaper',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='odurestructureboardpaper',
            name='date_submitted_to_pscb',
        ),
        migrations.RemoveField(
            model_name='odurestructureboardpaper',
            name='item_number',
        ),
        migrations.RemoveField(
            model_name='odurestructureboardpaper',
            name='meeting_number',
        ),
        migrations.RemoveField(
            model_name='odurestructureboardpaper',
            name='submitted_by',
        ),
    ]
