# Generated by Django 6.0.8 on 2026-08-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0243_remove_board_paper_manual_header_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_chairman', 'With Chairman for Endorsement'), ('chairman_approved', 'Chairman Endorsed'), ('circulated', 'Circulated to Members')], default='draft', help_text='Tracking: draft → with Chairman → endorsed → circulated.', max_length=24),
        ),
    ]
