# Generated by Django 6.0.8 on 2026-08-20 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0245_renumber_agenda_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('with_chairman', 'With Chairman for Endorsement'), ('circulated', 'Circulated to Members')], default='draft', help_text='Tracking: draft → with Chairman → endorsed → circulated.', max_length=24),
        ),
        migrations.CreateModel(
            name='SubmissionPrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_private_notes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='tracker.submission')),
            ],
            options={
                'unique_together': {('submission', 'author')},
            },
        ),
    ]
