# Generated by Django 6.0.8 on 2026-08-20 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0246_submission_private_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='chairman_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='chairman_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_reviewed_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='commissioner_circulated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='commissioner_review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='secretary_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='secretary_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_reviewed_minutes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='submitted_for_review_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_minutes_for_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minutes',
            name='tasks_allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minutes',
            name='tasks_allocated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_minutes_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_secretariat_review', 'Pending Secretary & Chairman Review'), ('reviewed', 'Reviewed'), ('circulated_to_commissioners', 'Circulated to Commissioners'), ('returned', 'Returned to Secretariat'), ('awaiting_signature', 'Awaiting Signature'), ('signed', 'Signed')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='MinutesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minutes_comments', to=settings.AUTH_USER_MODEL)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.minutes')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
