# Generated by Django 6.0.8 on 2026-08-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0247_minutes_chairman_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assessment_html',
            field=models.TextField(blank=True, default='', help_text='Sanitized rich-text assessment typed by the assigned principal/senior officer at Under Assessment, submitted via submit-to-manager. Display only — mirrors WorkflowEvent.remarks_html. Overwritten on resubmission.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assessment_text',
            field=models.TextField(blank=True, default='', help_text='Plain-text derivative of assessment_html, for search/export.'),
        ),
    ]
