# Generated by Django 6.0.8 on 2026-08-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0249_auditlog_hash_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempermission',
            name='is_enforced',
            field=models.BooleanField(default=True, help_text='P1-09, SCDMS Pre-Production Readiness Audit — Findings Register: whether any code path actually consults this permission. Several built-in codes (mainly core submission CRUD/workflow-transition verbs) exist here and are toggleable in the Role Definitions admin UI, but the submission lifecycle is actually governed entirely by hardcoded role checks in transitions.py — toggling those specific codes has no effect on system behavior. Kept in sync by hand — update this if a permission gains or loses its enforcement call site.'),
        ),
    ]
