# Generated by Django 6.0.8 on 2026-08-25 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0250_system_permission_is_enforced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudBackupConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('microsoft365', 'Microsoft 365 (OneDrive)')], help_text="One connection per provider — connecting again replaces the previous admin's connection for that provider.", max_length=20, unique=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reconnect', 'Needs reconnect'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('connected_email', models.EmailField(help_text="The M365 account's email, shown in the admin UI so it's obvious whose account backups are currently pushed to.", max_length=254)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_error', models.TextField(blank=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_backup_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cloud backup connection',
            },
        ),
    ]
