# Generated by Django 6.0.8 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0251_cloud_backup_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbackupconnection',
            name='provider',
            field=models.CharField(choices=[('google_drive', 'Google Drive')], help_text="One connection per provider — connecting again replaces the previous admin's connection for that provider.", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cloudbackupconnection',
            name='connected_email',
            field=models.EmailField(help_text="The Google account's email, shown in the admin UI so it's obvious whose account backups are currently pushed to.", max_length=254),
        ),
    ]
