# Generated by Django 6.0.8 on 2026-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0264_submission_draft_delegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('ipdu_manager', 'Manager IPDU'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal'), ('vipam_senior', 'VIPAM Senior Officer'), ('hr_unit_senior', 'HR Unit Senior Officer'), ('odu_senior', 'ODU Senior Officer'), ('csu_senior', 'CSU Senior Officer'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member'), ('hrmis_reviewer', 'Manager HRMIS (Read-Only Reviewer)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='roledefinition',
            name='role',
            field=models.CharField(choices=[('psc_admin', 'PSC Administrator'), ('receptionist', 'Receptionist'), ('psc_officer', 'PSC Officer'), ('psc_secretary', 'PSC Secretary'), ('senior_admin_officer', 'Senior Administration Officer'), ('psc_commissioner', 'PSC Commissioner'), ('chairperson', 'Chairperson, PSC'), ('psc_manager', 'OPSC Manager'), ('principal_officer', 'Principal Officer'), ('senior_officer', 'Senior Officer'), ('head_of_agency', 'Head of Agency (DG/Director)'), ('ministry_hr', 'Ministry HR Officer'), ('dept_admin', 'Department Admin Officer'), ('traveller', 'Public Servant (Travel)'), ('vipam_manager', 'VIPAM Manager'), ('hr_unit_manager', 'HR Unit Manager'), ('odu_manager', 'ODU Manager'), ('compliance_manager', 'Compliance Manager'), ('compliance_senior', 'Compliance Senior Officer'), ('csu_manager', 'CSU Manager'), ('ipdu_manager', 'Manager IPDU'), ('vipam_principal', 'VIPAM Principal'), ('hr_unit_principal', 'HR Unit Principal'), ('odu_principal', 'ODU Principal'), ('compliance_principal', 'Compliance Principal'), ('vipam_senior', 'VIPAM Senior Officer'), ('hr_unit_senior', 'HR Unit Senior Officer'), ('odu_senior', 'ODU Senior Officer'), ('csu_senior', 'CSU Senior Officer'), ('secretary_opsc', 'Secretary, OPSC'), ('dg_director', 'DG / Director (Ministry)'), ('commission_member', 'Commission Member'), ('panel_member', 'Investigation Panel Member'), ('hrmis_reviewer', 'Manager HRMIS (Read-Only Reviewer)')], max_length=50, unique=True),
        ),
    ]
