# Generated by Django 6.0.8 on 2026-09-09 23:41
# Hand-trimmed: autodetection also picked up the same pre-existing
# `choices=` metadata drift on Submission/RequiredDocument/WorkflowEvent
# stage fields noted in migrations 0268/0269 — out of scope here too,
# left untouched.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0269_chat_reactions_attachments_edit_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
