# Generated by Django 6.0.8 on 2026-09-10
# Hand-trimmed: autodetection also picked up the same pre-existing
# `choices=` metadata drift on Submission/RequiredDocument/WorkflowEvent
# stage fields noted in migrations 0268-0270 — out of scope here too,
# left untouched.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0270_conversationparticipant_muted'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
