# Generated by Django 6.0.8 on 2026-09-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0272_strip_duplicate_agenda_blurb_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(
                choices=[('en', 'English'), ('fr', 'Français'), ('bi', 'Bislama')],
                default='en',
                help_text=(
                    "Language for documents generated on this user's behalf (e.g. the "
                    "circulated agenda PDF/email) — kept in sync with the UI language "
                    "switcher, not just a per-device setting."
                ),
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name='AgendaCirculationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulation_receipts', to='tracker.meeting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_circulation_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['meeting_id', 'recipient_id'],
                'unique_together': {('meeting', 'recipient')},
            },
        ),
    ]
