# Generated by Django 6.0.8 on 2026-09-15

from django.db import migrations


def seed_localized_agenda_templates(apps, schema_editor):
    from tracker.email_templates import seed_default_email_templates

    seed_default_email_templates()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0273_agenda_circulation_i18n'),
    ]

    operations = [
        migrations.RunPython(seed_localized_agenda_templates, migrations.RunPython.noop),
    ]
